language: java

arch:
  - amd64
  - s390x

os: linux
dist: trusty

before_install:
  - |
    case "$(uname -m)" in
    (amd64|x86_64) printf '\1' | od -dAn | grep 1 ;;
    (s390x) printf '\1' | od -dAn | grep 256 ;;
    (*) echo unknown arch; uname -m; exit 1 ;;
    esac

install: true
script: ./mvnw install -DskipTests=true -Dgpg.skip=true -Dmaven.javadoc.skip=true

jdk:
  - openjdk15 # latest non-LTS release
  - openjdk11 # LTS release
  - openjdk8  # LTS release

jobs:
  include:
    - arch: amd64
      jdk: openjdk7 # target release on little-endian machine

    - arch: s390x
      jdk: openjdk7 # target release on big-endian machine
      install:
      - wget -O ibmjdk7.bin -q -T 1 -t 1 http://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/7.1.4.80/linux/s390x/ibm-java-sdk-7.1-4.80-s390x-archive.bin
      - echo "c8d61c9e1bdcee9a332fd46e2799d48fdc8f4568cf59545066539003822962d0  ibmjdk7.bin" | sha256sum -c -
      - chmod +x ibmjdk7.bin
      - echo "INSTALLER_UI=silent" > response.properties
      - echo "USER_INSTALL_DIR=$PWD/ibmjdk7" >> response.properties
      - echo "LICENSE_ACCEPTED=TRUE" >> response.properties
      - ./ibmjdk7.bin -i silent -f response.properties
      - export PATH="$PWD/ibmjdk7/bin:$PATH"
      - export JAVA_HOME="$PWD/ibmjdk7"
      - java -version

cache:
  directories:
    - $HOME/.m2
