== Zero-Allocation Hashing

==== Version 
[#image-maven]
[caption="", link=https://maven-badges.herokuapp.com/maven-central/net.openhft/zero-allocation-hashing]
image::https://maven-badges.herokuapp.com/maven-central/net.openhft/zero-allocation-hashing/badge.svg[]

=== Overview
This project provides a Java API for hashing any sequences of bytes in Java, including all kinds of
primitive arrays, buffers, `CharSequence`s and more. 

Written for Java 7+ under Apache 2.0 license.

The key difference compared to other similar projects, e.g. 
http://docs.guava-libraries.googlecode.com/git-history/release/javadoc/com/google/common/hash/package-summary.html[Guava hashing],
is that this has no object allocations during the hash computation and does not use `ThreadLocal`.

The implementation utilises native access where possible, but is also platform-endianness-agnostic.
This provides consistent results whatever the byte order, while only moderately affecting
performance.

Currently `long`-valued hash function interface is defined, with the following
implementations:

 - *https://github.com/Cyan4973/xxHash[xxHash]*.
 
 -  Two algorithms from *https://github.com/google/farmhash[FarmHash]*: `farmhashna` (introduced
 in FarmHash 1.0) and `farmhashuo` (introduced in FarmHash 1.1).
 
 - *https://code.google.com/p/cityhash/[CityHash], version 1.1* (latest; 1.1.1 is a C++
 language-specific maintenance release).

- *https://code.google.com/p/smhasher/wiki/MurmurHash3[MurmurHash3]*.

- *https://github.com/jandrewrogers/MetroHash[MetroHash]* (using the metrohash64_2 initialization vector).

- *https://github.com/wangyi-fudan/wyhash[wyHashV3]*.

These are thoroughly tested with JDK 7, 8, 9, 10, and 11 on little-endian platform.  However they
are believed to be independent from the native byte order.

==== Performance

Tested on Intel Core i7-4870HQ CPU @ 2.50GHz
|===
|Algorithm |Speed, GB/s |Bootstrap, ns

|xxHash |9.5 |6
|FarmHash `na` |9.0 |6
|FarmHash `uo` |7.2 |7
|CityHash |7.0 |7
|MurmurHash |5.3 |12
|WyHash |?? |??
|===

To sum up,

==== When to use Zero-Allocation Hashing
 * You need to hash plain byte sequences, memory blocks or "flat" objects.
 * You want zero-allocation and good performance (at Java scale).
 * You need hashing to be agile with regards to byte ordering.

==== When _not_ to use Zero-Allocation Hashing
 * You need to hash POJOs whose actual data is scattered in memory between managed objects.
   There is no simple way to hash these using this project, for example, classes such as:
+
[source, Java]
----
    class Person {
        String givenName, surName;
        int salary;
    }
----
   
 * You need to hash byte sequences of unknown length, for the simpliest example,
   `Iterator<Byte>`.
   
 * You need to transform the byte sequence (e.g. encode or decode it with a specific coding),
   and hash the resulting byte sequence on the way without dumping it to memory.

==== Java Doc
See http://javadoc.io/doc/net.openhft/zero-allocation-hashing/0.9

== Quick start

Gradle:
[source, groovy]
----
dependencies {
    compile 'net.openhft:zero-allocation-hashing:0.9'
}
----

Or Maven:
[source, xml]
----
<dependency>
  <groupId>net.openhft</groupId>
  <artifactId>zero-allocation-hashing</artifactId>
  <version>0.9</version>
</dependency>
----

In Java:
[source, Java]
----
long hash = LongHashFunction.xx().hashChars("hello");
----

See *http://openhft.github.io/Zero-Allocation-Hashing/apidocs/[JavaDocs]* for more information.

== Contributions are most welcome!

See the list of https://github.com/OpenHFT/Zero-Allocation-Hashing/issues[open issues].
