/*
 * Copyright 2013-2025 chronicle.software; SPDX-License-Identifier: Apache-2.0
 */
package net.openhft.hashing;

import org.junit.Test;

import java.nio.charset.StandardCharsets;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotEquals;

/**
 * Known-answer tests for the seed boundary between the C++ {@code uint32_t} contract and this
 * library's 64-bit extension.
 */
public class Murmur3SeedCompatibilityTest {

    private static final byte[] DATA = "The quick brown fox jumps over the lazy dog"
            .getBytes(StandardCharsets.UTF_8);

    // Generated by Austin Appleby's reference MurmurHash3_x64_128 implementation for DATA.
    private static final long[] CPP_SEED_80000000 = {
            0xace3941990e3b4e7L,
            0xda0d7c42fa300cd4L
    };

    private static final long[] CPP_SEED_FFFFFFFF = {
            0x691c1d73a800a18aL,
            0x647d67096440b412L
    };

    private static final long[] EXTENDED_SEED_MINUS_ONE = {
            0x7ddc2cae3c8061ceL,
            0xb3aa26abb775cf00L
    };

    @Test
    public void unsignedJavaIntMinimumMatchesCppReference() {
        final int seed = Integer.MIN_VALUE;
        assertBothApis(Integer.toUnsignedLong(seed), CPP_SEED_80000000);
    }

    @Test
    public void unsignedJavaIntMinusOneMatchesCppReference() {
        final int seed = -1;
        assertBothApis(Integer.toUnsignedLong(seed), CPP_SEED_FFFFFFFF);
    }

    @Test
    public void widenedNegativeIntUsesDocumented64BitExtension() {
        final int seed = -1;
        final long widenedSeed = seed;
        assertBothApis(widenedSeed, EXTENDED_SEED_MINUS_ONE);
        assertNotEquals(
                LongHashFunction.murmur_3(Integer.toUnsignedLong(seed)).hashBytes(DATA),
                LongHashFunction.murmur_3(widenedSeed).hashBytes(DATA));
    }

    private static void assertBothApis(final long seed, final long[] expected) {
        assertArrayEquals(expected, LongTupleHashFunction.murmur_3(seed).hashBytes(DATA));
        assertEquals(expected[0], LongHashFunction.murmur_3(seed).hashBytes(DATA));
    }
}
